project_id = "cqrvtaxjsurbcmkiowum"

[functions.save-video]
verify_jwt = true

[functions.create-folder]
verify_jwt = true

[functions.fetch-metadata]
verify_jwt = true

[functions.track-view]
verify_jwt = false
